---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
spec:
  project: default
  source:
    repoURL: https://github.com/ruadhan/gitops-cert-level-2-examples/
    targetRevision: HEAD
    path: ./environment-promotion/envs/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false